# Dockerfile for App Form image
FROM node:20

WORKDIR /App_Form


ENV PATH /App_Form/node_modules/.bin:$PATH

COPY ./App_Form/package.json ./
COPY ./App_Form/package-lock.json ./

RUN npm install --silent
RUN npm install react-scripts@5.0.1 -g --silent

EXPOSE 3000
