version: '3.8'

services:

  db_mongo:
    image: mongo
    container_name: db_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb_data/:/docker-entrypoint-initdb.d/

  db_mysql:
     image: mysql
     container_name: db_mysql
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     volumes:
       - ./sqlfiles/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  api_nodejs:
    image: api_nodejs
    container_name: api_nodejs
    restart: always
    build: .
    ports:
      - 5001:5001
    environment:
      - MONGODB_HOST=db_mongo
    depends_on:
      - db_mongo

  app_form:
    image: app_form
    container_name: app_form
    restart: always
    build:
      context: .
      dockerfile: ./
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_PORT=8000
    volumes:
      - ./App_Form/:/App_Form
      - /App_Form/node_modules
    depends_on:
      - api_nodejs
    command: npm run start
