# Dockerfile for API Python image
FROM python:3.10.12

WORKDIR /API_Python

RUN pip install --upgrade pip

COPY ./API_Python ./

RUN pip install --no-cache-dir flask flask-graphql flask-cors graphql-core mysql-connector

EXPOSE 5000

CMD [ "python3", "/API_Python/server.py" ]
